### PR TITLE
chore: Report file - add more info

### PR DESCRIPTION
**Pull request by mp-dthr**
Adding more info for specific metrics into report file. Most of the pipelines work with JUnit reporter, so it would be nice to have meaningful failure messages.

### CODE REVIEW

**Comment by mp-dthr** [comment]
@na-- Tagging you since noticed that you replied to other PRs. Please make a CR asap, thanks! 🙏

**Comment by na--** [comment]
@mp-dthr , I see we forgot to put the link to the main repo for the end-of-test summary jslib functions, but this is it: https://github.com/grafana/k6-jslib-summary

Can you please make your PR in there, so we can actually review it. This repo is used only for the published releases, not the actual development.

**Comment by mp-dthr** [comment]
Thanks for your quick reply @na-- ! 🙇 
I have cloned this repo, but don't have permissions to push:
`remote: Permission to grafana/k6-jslib-summary.git denied to mp-dthr.`

**Comment by na--** [comment]
You don't have permission to push to this repo too :sweat_smile: You have to fork the repo first, push the changed branch to your copy of the repo and then make the pull request from there, the same as you did for this pull request

**Comment by mp-dthr** [comment]
@na-- , here it is -> https://github.com/grafana/k6-jslib-summary/pull/5.

**Pull request closed without merging**
