### PR TITLE
Add k6-jslib-aws v0.4.0

### PR DESCRIPTION
**Pull request by oleiade**
We have published v0.4.0 of [k6-jslib-aws](https://github.com/grafana/k6-jslib-aws). This [version](https://github.com/grafana/k6-jslib-aws/releases/tag/v0.4.0) brings minor changes, and refactors to the existing version.

This PR bumps k6-jslib-aws version to reflect that.

### CODE REVIEW

**Review by javaducky — CHANGES_REQUESTED** [review]
With the new version, your test cases (in `tests/aws.js`) should be bumped to use the new library.

**Comment by oleiade** [comment]
@javaducky fixed 🙇🏻

**Comment by javaducky** [comment]
Sadly this jslib process is a bit painful, but changes LGTM.

Just a personal nitpick though...probably should not squash commits once a PR is in progress as this makes it difficult for reviewers to verify issues have been resolved without doing a full review---for this PR, no big deal. I'd suggest using the option to squash commits when merging.

**Review by javaducky — APPROVED** [review]

**Comment by oleiade** [comment]
Thanks for the feedback @javaducky! In general, I adapt my workflow case by case: but my natural preference is to squash/rebase for as long as there are no approvals, and to mark review comments as resolved along the way. I'll switch to fixup! Commits that I'll rebase autosquash before merging   in this repo then.

I also have some feedback on my end though 😸 It would make my life easier if you could use the review feature instead of comments. It's no big deal on small PRs really, but on larger ones with multiple reviewers and a lot of change requests, it makes it much easier for me to keep track of what I have already addressed or not. Please let me know if that works for you 🤝

**Pull request merged**
